name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Making the Environment leaner
      run: sudo snap list && sudo snap remove firefox && sudo apt remove -y snapd

    - name: Update Environment
      run: sudo apt update -y

    - name: Install Dependencies
      run: |
        sudo apt install -y git-core gnupg build-essential zip \
        curl libarchive-tools flex \
        unzip python3 python3-pip python3-dev \
        python-is-python3 ccache libncurses5-dev lzop \
        patchelf git-lfs ripgrep &> /dev/null

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 14
        platform: x64

    - name: KernelSU Next with SUSFS
      run: | 
        curl -LSs "https://raw.githubusercontent.com/DarkS1di/KernelSU-Next/next-susfs_v1.5.5-v1.5.7/kernel/setup.sh" | bash -s next-susfs_v1.5.5-v1.5.7

    - name: Apply SUSFS patches
      run: |
        export KERNEL_ROOT=$GITHUB_WORKSPACE

        echo "Applying SUSFS patches..."
        cp ./kernel_patches/50_add_susfs_in_kernel-*.patch $KERNEL_ROOT/

        cp ./kernel_patches/fs/* $KERNEL_ROOT/fs/
        cp ./kernel_patches/include/linux/* $KERNEL_ROOT/include/linux/

        cd $KERNEL_ROOT
        patch -p1 < 50_add_susfs_in_kernel-*.patch || echo "Manual patch may be required"

    - name: Download Neutron Toolchain
      run: bash scripts/hani-ci.sh --tools

    - name: Build hanikrnl.
      run: bash scripts/hani-ci.sh --build

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: hanikrnl
        path: 4.19-hanikrnl.*-chime*.zip
